# ≈‰÷√

server:
  port: 8888

spring:
  jackson:
    serialization:
      indent_output: true

management:
  security:
    enabled: false

info:
  contact:
    email: master@anxpp.com

endpoints:
  shutdown:
    enabled: false